//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_Master()
        {
            this.Sales_Order_Details = new HashSet<Sales_Order_Details>();
        }
    
        public string ProductNo { get; set; }
        public string Description { get; set; }
        public decimal ProfitPerc { get; set; }
        public string UnitMeasure { get; set; }
        public decimal QtyonHand { get; set; }
        public decimal ReorderLvl { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Order_Details> Sales_Order_Details { get; set; }
    }
}
