//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sales_Order()
        {
            this.Sales_Order_Details = new HashSet<Sales_Order_Details>();
        }
    
        public string OrderNo { get; set; }
        public string ClientNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string DelyAddr { get; set; }
        public string SalesManNo { get; set; }
        public string DelyType { get; set; }
        public string BilledYn { get; set; }
        public Nullable<System.DateTime> DelyDate { get; set; }
        public string OrderStatus { get; set; }
    
        public virtual Client_Master Client_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Order_Details> Sales_Order_Details { get; set; }
        public virtual Salesman_Master Salesman_Master { get; set; }
    }
}
