//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Order_Details
    {
        public string OrderNo { get; set; }
        public string ProductNo { get; set; }
        public Nullable<decimal> QtyOrdered { get; set; }
        public Nullable<decimal> QtyDisp { get; set; }
        public Nullable<decimal> ProductRate { get; set; }
    
        public virtual Product_Master Product_Master { get; set; }
        public virtual Sales_Order Sales_Order { get; set; }
    }
}
